/* automatically generated by ./build/bin/build-entry.js */

import Alert from "./components/alert/index.js"
import Button from "./components/button/index.js"
//import locale from 'zelement/src/locale'; // temp to comment the locale file

const components = [
     Alert,
 Button,
    //CollapseTransition
];

const install = function(Vue,opts={}){
    //locale.use(opt.locale);
    //locale.i18n(opt.i18n);//i18n is to make international things.

    components.forEach(component=>{
        Vue.component(component.name,component);
    });

    // Vue.use(InfiniteScroll);
    // Vue.use(Loading.directive);

    // Vue.prototype.$ELEMENT = {
    //     size: opts.size || '',
    //     zIndex: opts.zIndex || 2000
    // };

    // Vue.prototype.$loading = Loading.service;
    // Vue.prototype.$msgbox = MessageBox;
    // Vue.prototype.$alert = MessageBox.alert;
    // Vue.prototype.$confirm = MessageBox.confirm;
    // Vue.prototype.$prompt = MessageBox.prompt;
    // Vue.prototype.$notify = Notification;
    // Vue.prototype.$message = Message;
};

/* istanbul ignore if */ // 这部分的代码是进行代码覆盖时的ignore的标识
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.19',
  // locale: locale.use,
  // i18n: locale.i18n,
  install, // install 这个语句是必须的，用于向vue中注入组件
  // CollapseTransition,
  // Loading,
  Alert,
  Button
}